### ISSUE TITLE
How to make public the xml

### ISSUE THREAD

**Issue by checho221** [GautamGupta/YOURLS-Import-Export#7]
Hi there!

I want to make public the xml in order to handle the results to show in another web page. and how can i get the nonce=xxxxx token every time i exec file_get_contents() in my php file.

Thanks in advance!!

**Comment by GautamGupta** [comment]
Comment out this line https://github.com/GautamGupta/YOURLS-Import-Export/blob/master/plugin.php#L108

**Comment by checho221** [comment]
thanks, but it doesn´t solve the issue, how to make public the resulting XML??

Thanks in advance.
